### PR TITLE
Added new per display scripts.

### PR DESCRIPTION
**Pull request by laserswald**
Use current_disp, geo_disp, and ls_disp to build multihead-aware scripts. fullscreen_disp is an example of this.

### CODE REVIEW

**Comment by joaopms** [comment]
I love you.

**Comment by greduan** [comment]
So... This gives us access to multiple workspaces and stuff?

**Comment by laserswald** [comment]
@greduan No, this gives support for building scripts that can use multihead. 

**ls_disp** lists all your displays.
**geo_disp**, when given a display, returns the relative display size or the coordinates of the top left corner and bottom right corner, if given the -a flag. 
**current_disp**, when given x and y coordinates, returns which display those coordinates are in. 

I made these because I can't give up multihead and I have literally the worst monitor setup imaginable.

**Comment by z3bra** [comment]
It would be nice to have these be actual tools rather than shell scripts relying on xrandr and others.

Actually, contrib is meant to showcase the possibilities of wmutils as standalone tools. The fact this one relies on other tools proves that wmutils lacks some features, which is considered a bug as it aims for completeness.

**Comment by laserswald** [comment]
I have been snooping around the libraries you guys are using and these
things should be possible. I'll open an issue and another pull request
there, since it looks like you guys have some great visions on how the
core is supposed to function.

Meanwhile, these scripts work, so if someone wants them, they can clone
my repo, or I can move them somewhere else.

**Comment by z3bra** [comment]
We'll be glad to integrate such tools in core. I'll try to work on them myself too.
I won't merge your scripts though, as they don't fit the contrib/ "spirit". But these are really nice ones indeed, and they can be pretty handy. I'll menion them whenever someone asks about multihead support.

That's a discussion we had with dcat, wondering how wmutils should handle multiheads. We did not really found an answer about it yet, and such tools would happily solve the issue. Maybe I should open a feature request to open the discussion about it.

**Comment by dcat** [comment]
Shouldn't listing off the displays be as simple as iterating though the logical order of `$DISPLAY` until `lsw` (or any other of our programs) returns 1? (indicating the connection is broken, and in this case that screen doesn't exist)

And as for checking the screen size, should't it be enough to run `wattr wh $(lsw -r)` with the according `$DISPLAY`?

**Comment by z3bra** [comment]
By display, I think he means "monitors". I just tried with only one monitor on my setup, and something like `for MON in 0 1 2 3; do DISPLAY=:0.$MON wattr wh $(lsw -r); done` returns the same result 4 times.

**Comment by dcat** [comment]
If this is `Xinerama` related, please `s/multihead/Xinerama/g`.

**Comment by z3bra** [comment]
I don't know if such a behavior would rely on `Xinerama`. But I think this is something we could investigate on. I just don't happen to have multiple monitors, so this is not something I can work on (or will use)

**Comment by laserswald** [comment]
Nope, using @z3bratabs 's one liner doesn't give me any difference in the sizes of the resolutions - it only gives me the large stitched together root window's dimensions. 
I can definitely work on this, I have probably the worst case with multi monitors. One of my monitors is portrait and one is landscape, so I have giant unused spaces that we have to deal with; we won't miss any problems with those, at least.

**Pull request closed without merging**
