### PR TITLE
closest.sh: only call focus if function returned data

### PR DESCRIPTION
**Pull request by lwilletts**

### CODE REVIEW

**Comment by z3bra** [comment]
```
./closest.sh: 39: ./closest.sh: Syntax error: word unexpected (expecting ")")
```

Please try your patch before submitting.

**Comment by lwilletts** [comment]
Oops, Fixed.

**Comment by z3bra** [comment]
For future reference, `test ! -z` is the same as `test -n`

**Comment by lwilletts** [comment]
Yes, I am aware, but prefer using the ! symbol to indicate to me 'NOT' empty.

**Pull request merged**
